# Generated by Django 4.2.23 on 2025-08-12 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.branch')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='core.shift')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'branch', 'shift')},
            },
        ),
    ]
