# Generated by Django 4.2.23 on 2025-08-12 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='core.academicsession'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('name', 'branch', 'shift', 'academic_session')},
        ),
    ]
