# Generated by Django 4.2.23 on 2025-08-13 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_academicsession_alter_schoolclass_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('name', 'branch', 'shift')},
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='academic_session',
        ),
    ]
