# Generated by Django 4.2.23 on 2025-08-13 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_schoolclass_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('name', 'branch')},
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='shift',
        ),
    ]
